/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkVisaRouteImport } from './routes/work-visa'
import { Route as TouristVisaRouteImport } from './routes/tourist-visa'
import { Route as StudentVisaRouteImport } from './routes/student-visa'
import { Route as CountriesRouteImport } from './routes/countries'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const WorkVisaRoute = WorkVisaRouteImport.update({
  id: '/work-visa',
  path: '/work-visa',
  getParentRoute: () => rootRouteImport,
} as any)
const TouristVisaRoute = TouristVisaRouteImport.update({
  id: '/tourist-visa',
  path: '/tourist-visa',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentVisaRoute = StudentVisaRouteImport.update({
  id: '/student-visa',
  path: '/student-visa',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesRoute = CountriesRouteImport.update({
  id: '/countries',
  path: '/countries',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/countries': typeof CountriesRoute
  '/student-visa': typeof StudentVisaRoute
  '/tourist-visa': typeof TouristVisaRoute
  '/work-visa': typeof WorkVisaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/countries': typeof CountriesRoute
  '/student-visa': typeof StudentVisaRoute
  '/tourist-visa': typeof TouristVisaRoute
  '/work-visa': typeof WorkVisaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/countries': typeof CountriesRoute
  '/student-visa': typeof StudentVisaRoute
  '/tourist-visa': typeof TouristVisaRoute
  '/work-visa': typeof WorkVisaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/countries'
    | '/student-visa'
    | '/tourist-visa'
    | '/work-visa'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/countries'
    | '/student-visa'
    | '/tourist-visa'
    | '/work-visa'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/countries'
    | '/student-visa'
    | '/tourist-visa'
    | '/work-visa'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  CountriesRoute: typeof CountriesRoute
  StudentVisaRoute: typeof StudentVisaRoute
  TouristVisaRoute: typeof TouristVisaRoute
  WorkVisaRoute: typeof WorkVisaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/work-visa': {
      id: '/work-visa'
      path: '/work-visa'
      fullPath: '/work-visa'
      preLoaderRoute: typeof WorkVisaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tourist-visa': {
      id: '/tourist-visa'
      path: '/tourist-visa'
      fullPath: '/tourist-visa'
      preLoaderRoute: typeof TouristVisaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-visa': {
      id: '/student-visa'
      path: '/student-visa'
      fullPath: '/student-visa'
      preLoaderRoute: typeof StudentVisaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countries': {
      id: '/countries'
      path: '/countries'
      fullPath: '/countries'
      preLoaderRoute: typeof CountriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  CountriesRoute: CountriesRoute,
  StudentVisaRoute: StudentVisaRoute,
  TouristVisaRoute: TouristVisaRoute,
  WorkVisaRoute: WorkVisaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
